version: '3.9'
volumes:
    pgdata: {}

services:
    postgresql:
        env_file:
            - .env
        container_name: postgresql
        build:
            context: ./requirements/postgresql
            dockerfile: Dockerfile
        ports:
            - "5432:5432"
        networks:
            - app
        tty: true
        volumes:
            - pgdata:/var/lib/postgresql/data

    nestjs:
        env_file:
            - .env
        container_name: nestjs
        build:
            context: ./requirements/nestjs
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        networks:
            - app
        tty: true
        depends_on:
            - postgresql

networks:
    app:
        driver: bridge